version: '3.8'
services:
  backend:
    build: ./backend
    environment:
      - DATABASE_HOST=db  # Make sure this is set to the service name of your MySQL service
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=finalproject
    depends_on:
      - db
    ports:
      - "3500:3500"
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=finalproject
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
